GO

-- enable queue processing
ALTER QUEUE [dbo].[NewPriceInitiatorQueue] WITH STATUS = ON , RETENTION = OFF , POISON_MESSAGE_HANDLING (STATUS = OFF) 
	, ACTIVATION (   STATUS = ON ,
        PROCEDURE_NAME = [dbo].[ConfirmProcessNewPrice], MAX_QUEUE_READERS = 1, EXECUTE AS OWNER) ; 

GO

ALTER QUEUE [dbo].[NewPriceTargetQueue] WITH STATUS = ON , RETENTION = OFF , POISON_MESSAGE_HANDLING (STATUS = OFF)
	, ACTIVATION (  STATUS = ON ,
        PROCEDURE_NAME = [dbo].[ProcessNewPrice], MAX_QUEUE_READERS = 1, EXECUTE AS OWNER) ; 

GO
